version: '3'
services:
  frontend:
    build:
      context: ./frontend
    image: frontend:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./proxy.template:/etc/nginx/conf.d/proxy.template"
      - "/etc/letsencrypt:/etc/letsencrypt"
    environment:
      - SERVER=${SERVER}
    command: /bin/sh -c "envsubst '$$SERVER' < /etc/nginx/conf.d/proxy.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  backend:
    build:
      context: ./backend
    image: backend:latest
    ports:
      - "8080:8080"
