version: '3.7'
services:
  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    image: ollywelch/webapp-frontend:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./proxy.template:/etc/nginx/conf.d/proxy.template"
      - "/etc/letsencrypt:/etc/letsencrypt"
    environment:
      - SERVER=${SERVER}
    command: /bin/sh -c "envsubst '$$SERVER' < /etc/nginx/conf.d/proxy.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  backend:
    build:
      context: ./backend
    depends_on:
      - postgresdb
    image: ollywelch/webapp-backend:latest
    ports:
      - "8080:8080"
  postgresdb:
    image: postgres:latest
    environment:
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB=webapp
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    secrets:
      - postgres_user
      - postgres_password
    ports:
      - "5432:5432"
secrets:
  postgres_user:
    external: true
  postgres_password:
    external: true
volumes:
  pgdata:
